###
POST http://localhost:5050/users/adduser 
Content-Type: application/json

{
    "username": "mark",
    "email": "mark@email.com",
    "password": "1234"
}

####
POST http://localhost:5050/users/login HTTP/1.1
Content-Type: application/json

{
    "username": "mark",
    "password": "1234"
}

// get all question
###
GET http://localhost:4040/
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.Mg.wc92jKSt7QF0CaLGvP4PllfwzyEssEauUDoF_58jOtc

// add a question
###
POST http://localhost:4040/addquestion
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.Mg.wc92jKSt7QF0CaLGvP4PllfwzyEssEauUDoF_58jOtc

{
    "question_title": "SQL select",
    "question" : "<p>SELECT</code> statement:</p>"
}

// get a specific question
###
GET http://localhost:4040/5
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.Mg.wc92jKSt7QF0CaLGvP4PllfwzyEssEauUDoF_58jOtc

//delete a question
###
DELETE http://localhost:4040/deletequestion/3
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.Mg.wc92jKSt7QF0CaLGvP4PllfwzyEssEauUDoF_58jOtc

// add an answer
###
POST http://localhost:4040/addanswer
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.Mg.wc92jKSt7QF0CaLGvP4PllfwzyEssEauUDoF_58jOtc

{
    "question_id": 2,
    "answer" : "<p>In <strong>SQL Server</strong>, it is possible to insert rows into a table with an <code>INSERT.. SELECT</code> statement:</p>"
}


// adding a like
###
POST http://localhost:4040/addlike
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.Mg.wc92jKSt7QF0CaLGvP4PllfwzyEssEauUDoF_58jOtc

{
    "answer_id": 2
}


// adding a dislike
###
POST http://localhost:4040/adddislike
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.Mg.wc92jKSt7QF0CaLGvP4PllfwzyEssEauUDoF_58jOtc

{
    "answer_id": 2
}

//search a question
###
GET http://localhost:4040/search/kkk 
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.Mg.wc92jKSt7QF0CaLGvP4PllfwzyEssEauUDoF_58jOtc

/// add a comment
###
POST http://localhost:4040/addcomment
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.Mg.wc92jKSt7QF0CaLGvP4PllfwzyEssEauUDoF_58jOtc

{
    "answer_id": 2,
    "comment": "this the most suitable answer found"
}

/// get user questions
###
GET http://localhost:4040/getmyquestion/2 
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.Mg.wc92jKSt7QF0CaLGvP4PllfwzyEssEauUDoF_58jOtc

///get mostly answered question
###
GET http://localhost:4040/mostlyanswered 
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.Mg.wc92jKSt7QF0CaLGvP4PllfwzyEssEauUDoF_58jOtc


/// set prefered answer
###
PATCH  http://localhost:4040/setPreferedanswer
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.Mg.wc92jKSt7QF0CaLGvP4PllfwzyEssEauUDoF_58jOtc

{
    "answer_id": 2
}

###
/// get answers for a given question
GET http://localhost:4040/answers/2
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.Mg.wc92jKSt7QF0CaLGvP4PllfwzyEssEauUDoF_58jOtc
